//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var FamilyStatus = &struct {
	Unknown postgres.StringExpression
	Single  postgres.StringExpression
	Married postgres.StringExpression
}{
	Unknown: postgres.NewEnumValue("unknown"),
	Single:  postgres.NewEnumValue("single"),
	Married: postgres.NewEnumValue("married"),
}
