//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ReportKind = &struct {
	Event                postgres.StringExpression
	Business             postgres.StringExpression
	ProjectParticipation postgres.StringExpression
	DailyCheckups        postgres.StringExpression
}{
	Event:                postgres.NewEnumValue("event"),
	Business:             postgres.NewEnumValue("business"),
	ProjectParticipation: postgres.NewEnumValue("project_participation"),
	DailyCheckups:        postgres.NewEnumValue("daily_checkups"),
}
